# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(verbose_name='Event start date & time')),
                ('end', models.DateTimeField(verbose_name='Event end date & time')),
                ('project_id', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64)),
                ('project_description', models.CharField(max_length=512)),
                ('project_color', models.CharField(max_length=6)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
