# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=64)),
                ('activity_color', models.CharField(max_length=6)),
                ('activity_created_date', models.DateField()),
                ('activity_modified_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=64)),
                ('client_created_date', models.DateField()),
                ('client_modified_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(verbose_name='Event began')),
                ('end', models.DateTimeField(verbose_name='Event ended')),
                ('event_created_date', models.DateField()),
                ('event_modified_date', models.DateField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64)),
                ('project_description', models.CharField(max_length=512)),
                ('project_color', models.CharField(max_length=6)),
                ('project_created_date', models.DateField()),
                ('project_modified_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(db_column='client_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ts_app.Client')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ts_app.Project'),
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
